"use client"


import './globals.css'
import Auth from './provider';
import {Providers} from "./providers";
import { Inter } from 'next/font/google'
import { IKContext } from 'imagekitio-react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <IKContext   publicKey="public_A5z/FWs66g4clXomlrG255YQlTg="

urlEndpoint="https://ik.imagekit.io/c0z5bhoikn"

transformationPosition="path"

authenticationEndpoint="https://dhaage.heisenberg.in.net/"  > <Providers> <Auth> {children}  </Auth>  </Providers > </IKContext>  </body>
    </html>
  )
}
